// Fiksna lista zemalja porekla (stavka 42): generisano iz koncept/zemlje-iso-kodovi.csv.
// Postavlja se jednom, nije editabilna od strane korisnika.
export interface Zemlja { naziv: string; kod: string }

export const ZEMLJE: Zemlja[] = [
  { naziv: "Albanija", kod: "AL" },
  { naziv: "Alžir", kod: "DZ" },
  { naziv: "Američka Devičanska ostrva", kod: "VI" },
  { naziv: "Američka Samoa", kod: "AS" },
  { naziv: "Andora", kod: "AD" },
  { naziv: "Angola", kod: "AO" },
  { naziv: "Angvila", kod: "AI" },
  { naziv: "Antarktik", kod: "AQ" },
  { naziv: "Antigva i Barbuda", kod: "AG" },
  { naziv: "Argentina", kod: "AR" },
  { naziv: "Armenija", kod: "AM" },
  { naziv: "Aruba", kod: "AW" },
  { naziv: "Australija", kod: "AU" },
  { naziv: "Austrija", kod: "AT" },
  { naziv: "Avganistan", kod: "AF" },
  { naziv: "Azerbejdžan", kod: "AZ" },
  { naziv: "Bahami", kod: "BS" },
  { naziv: "Bahrein", kod: "BH" },
  { naziv: "Bangladeš", kod: "BD" },
  { naziv: "Barbados", kod: "BB" },
  { naziv: "Belgija", kod: "BE" },
  { naziv: "Belize", kod: "BZ" },
  { naziv: "Belorusija", kod: "BY" },
  { naziv: "Benin", kod: "BJ" },
  { naziv: "Bermuda", kod: "BM" },
  { naziv: "Bocvana", kod: "BW" },
  { naziv: "Bolivija", kod: "BO" },
  { naziv: "Boner, Sint Eustatijus i Saba", kod: "BQ" },
  { naziv: "Bosna i Hercegovina", kod: "BA" },
  { naziv: "Božićno ostrvo", kod: "CX" },
  { naziv: "Brazil", kod: "BR" },
  { naziv: "Britanska Devičanska ostrva", kod: "VG" },
  { naziv: "Britanska teritorija u Indijskom okeanu", kod: "IO" },
  { naziv: "Brunej", kod: "BN" },
  { naziv: "Bugarska", kod: "BG" },
  { naziv: "Burkina Faso", kod: "BF" },
  { naziv: "Burundi", kod: "BI" },
  { naziv: "Butan", kod: "BT" },
  { naziv: "Buve ostrvo", kod: "BV" },
  { naziv: "Čad", kod: "TD" },
  { naziv: "Centralnoafrička Republika", kod: "CF" },
  { naziv: "Češka", kod: "CZ" },
  { naziv: "Čile", kod: "CL" },
  { naziv: "Crna Gora", kod: "ME" },
  { naziv: "Danska", kod: "DK" },
  { naziv: "Demokratska Republika Kongo", kod: "CD" },
  { naziv: "Dominika", kod: "DM" },
  { naziv: "Dominikanska Republika", kod: "DO" },
  { naziv: "Džerzi", kod: "JE" },
  { naziv: "Džibuti", kod: "DJ" },
  { naziv: "Egipat", kod: "EG" },
  { naziv: "Ekvador", kod: "EC" },
  { naziv: "Ekvatorijalna Gvineja", kod: "GQ" },
  { naziv: "Eritreja", kod: "ER" },
  { naziv: "Estonija", kod: "EE" },
  { naziv: "Esvatini", kod: "SZ" },
  { naziv: "Etiopija", kod: "ET" },
  { naziv: "Farska ostrva", kod: "FO" },
  { naziv: "Fidži", kod: "FJ" },
  { naziv: "Filipini", kod: "PH" },
  { naziv: "Finska", kod: "FI" },
  { naziv: "Foklandska ostrva", kod: "FK" },
  { naziv: "Francuska", kod: "FR" },
  { naziv: "Francuska Gvajana", kod: "GF" },
  { naziv: "Francuska Polinezija", kod: "PF" },
  { naziv: "Francuske južne teritorije", kod: "TF" },
  { naziv: "Gabon", kod: "GA" },
  { naziv: "Gambija", kod: "GM" },
  { naziv: "Gana", kod: "GH" },
  { naziv: "Gernzi", kod: "GG" },
  { naziv: "Gibraltar", kod: "GI" },
  { naziv: "Grčka", kod: "GR" },
  { naziv: "Grenada", kod: "GD" },
  { naziv: "Grenland", kod: "GL" },
  { naziv: "Gruzija", kod: "GE" },
  { naziv: "Guam", kod: "GU" },
  { naziv: "Gvadelupe", kod: "GP" },
  { naziv: "Gvajana", kod: "GY" },
  { naziv: "Gvatemala", kod: "GT" },
  { naziv: "Gvineja", kod: "GN" },
  { naziv: "Gvineja Bisao", kod: "GW" },
  { naziv: "Haiti", kod: "HT" },
  { naziv: "Herdovo ostrvo i ostrva Mekdonald", kod: "HM" },
  { naziv: "Holandija", kod: "NL" },
  { naziv: "Honduras", kod: "HN" },
  { naziv: "Hong Kong", kod: "HK" },
  { naziv: "Hrvatska", kod: "HR" },
  { naziv: "Indija", kod: "IN" },
  { naziv: "Indonezija", kod: "ID" },
  { naziv: "Irak", kod: "IQ" },
  { naziv: "Iran", kod: "IR" },
  { naziv: "Irska", kod: "IE" },
  { naziv: "Island", kod: "IS" },
  { naziv: "Istočni Timor", kod: "TL" },
  { naziv: "Italija", kod: "IT" },
  { naziv: "Izrael", kod: "IL" },
  { naziv: "Jamajka", kod: "JM" },
  { naziv: "Japan", kod: "JP" },
  { naziv: "Jemen", kod: "YE" },
  { naziv: "Jordan", kod: "JO" },
  { naziv: "Južna Džordžija i Južna Sendvička ostrva", kod: "GS" },
  { naziv: "Južna Koreja", kod: "KR" },
  { naziv: "Južni Sudan", kod: "SS" },
  { naziv: "Južnoafrička Republika", kod: "ZA" },
  { naziv: "Kajmanska ostrva", kod: "KY" },
  { naziv: "Kambodža", kod: "KH" },
  { naziv: "Kamerun", kod: "CM" },
  { naziv: "Kanada", kod: "CA" },
  { naziv: "Katar", kod: "QA" },
  { naziv: "Kazahstan", kod: "KZ" },
  { naziv: "Kenija", kod: "KE" },
  { naziv: "Kina", kod: "CN" },
  { naziv: "Kipar", kod: "CY" },
  { naziv: "Kirasao", kod: "CW" },
  { naziv: "Kirgistan", kod: "KG" },
  { naziv: "Kiribati", kod: "KI" },
  { naziv: "Kokosova (Keling) ostrva", kod: "CC" },
  { naziv: "Kolumbija", kod: "CO" },
  { naziv: "Komori", kod: "KM" },
  { naziv: "Kongo", kod: "CG" },
  { naziv: "Kostarika", kod: "CR" },
  { naziv: "Kuba", kod: "CU" },
  { naziv: "Kukova ostrva", kod: "CK" },
  { naziv: "Kuvajt", kod: "KW" },
  { naziv: "Laos", kod: "LA" },
  { naziv: "Lesoto", kod: "LS" },
  { naziv: "Letonija", kod: "LV" },
  { naziv: "Liban", kod: "LB" },
  { naziv: "Liberija", kod: "LR" },
  { naziv: "Libija", kod: "LY" },
  { naziv: "Lihtenštajn", kod: "LI" },
  { naziv: "Litvanija", kod: "LT" },
  { naziv: "Luksemburg", kod: "LU" },
  { naziv: "Madagaskar", kod: "MG" },
  { naziv: "Mađarska", kod: "HU" },
  { naziv: "Majot", kod: "YT" },
  { naziv: "Makao", kod: "MO" },
  { naziv: "Malavi", kod: "MW" },
  { naziv: "Maldivi", kod: "MV" },
  { naziv: "Malezija", kod: "MY" },
  { naziv: "Mali", kod: "ML" },
  { naziv: "Malta", kod: "MT" },
  { naziv: "Manja udaljena ostrva SAD", kod: "UM" },
  { naziv: "Maroko", kod: "MA" },
  { naziv: "Maršalska ostrva", kod: "MH" },
  { naziv: "Martinik", kod: "MQ" },
  { naziv: "Mauricijus", kod: "MU" },
  { naziv: "Mauritanija", kod: "MR" },
  { naziv: "Meksiko", kod: "MX" },
  { naziv: "Mikronezija", kod: "FM" },
  { naziv: "Mjanmar", kod: "MM" },
  { naziv: "Moldavija", kod: "MD" },
  { naziv: "Monako", kod: "MC" },
  { naziv: "Mongolija", kod: "MN" },
  { naziv: "Monserat", kod: "MS" },
  { naziv: "Mozambik", kod: "MZ" },
  { naziv: "Namibija", kod: "NA" },
  { naziv: "Nauru", kod: "NR" },
  { naziv: "Nemačka", kod: "DE" },
  { naziv: "Nepal", kod: "NP" },
  { naziv: "Niger", kod: "NE" },
  { naziv: "Nigerija", kod: "NG" },
  { naziv: "Nikaragva", kod: "NI" },
  { naziv: "Niue", kod: "NU" },
  { naziv: "Norfolško ostrvo", kod: "NF" },
  { naziv: "Norveška", kod: "NO" },
  { naziv: "Nova Kaledonija", kod: "NC" },
  { naziv: "Novi Zeland", kod: "NZ" },
  { naziv: "Obala Slonovače", kod: "CI" },
  { naziv: "Olandska ostrva", kod: "AX" },
  { naziv: "Oman", kod: "OM" },
  { naziv: "Ostrvo Man", kod: "IM" },
  { naziv: "Pakistan", kod: "PK" },
  { naziv: "Palau", kod: "PW" },
  { naziv: "Palestina", kod: "PS" },
  { naziv: "Panama", kod: "PA" },
  { naziv: "Papua Nova Gvineja", kod: "PG" },
  { naziv: "Paragvaj", kod: "PY" },
  { naziv: "Peru", kod: "PE" },
  { naziv: "Pitkern", kod: "PN" },
  { naziv: "Poljska", kod: "PL" },
  { naziv: "Portoriko", kod: "PR" },
  { naziv: "Portugal", kod: "PT" },
  { naziv: "Reinion", kod: "RE" },
  { naziv: "Ruanda", kod: "RW" },
  { naziv: "Rumunija", kod: "RO" },
  { naziv: "Rusija", kod: "RU" },
  { naziv: "Salvador", kod: "SV" },
  { naziv: "Samoa", kod: "WS" },
  { naziv: "San Marino", kod: "SM" },
  { naziv: "Sao Tome i Principe", kod: "ST" },
  { naziv: "Saudijska Arabija", kod: "SA" },
  { naziv: "Sejšeli", kod: "SC" },
  { naziv: "Sen Bartelemi", kod: "BL" },
  { naziv: "Sen Marten (francuski deo)", kod: "MF" },
  { naziv: "Sen Pjer i Mikelon", kod: "PM" },
  { naziv: "Senegal", kod: "SN" },
  { naziv: "Severna Koreja", kod: "KP" },
  { naziv: "Severna Makedonija", kod: "MK" },
  { naziv: "Severna Marijanska ostrva", kod: "MP" },
  { naziv: "Sijera Leone", kod: "SL" },
  { naziv: "Singapur", kod: "SG" },
  { naziv: "Sint Marten (holandski deo)", kod: "SX" },
  { naziv: "Sirija", kod: "SY" },
  { naziv: "Sjedinjene Američke Države", kod: "US" },
  { naziv: "Slovačka", kod: "SK" },
  { naziv: "Slovenija", kod: "SI" },
  { naziv: "Solomonska ostrva", kod: "SB" },
  { naziv: "Somalija", kod: "SO" },
  { naziv: "Španija", kod: "ES" },
  { naziv: "Srbija", kod: "RS" },
  { naziv: "Šri Lanka", kod: "LK" },
  { naziv: "Sudan", kod: "SD" },
  { naziv: "Surinam", kod: "SR" },
  { naziv: "Švajcarska", kod: "CH" },
  { naziv: "Svalbard i Jan Majen", kod: "SJ" },
  { naziv: "Švedska", kod: "SE" },
  { naziv: "Sveta Jelena, Ascension i Tristan da Kunja", kod: "SH" },
  { naziv: "Sveta Lucija", kod: "LC" },
  { naziv: "Sveti Kits i Nevis", kod: "KN" },
  { naziv: "Sveti Vinsent i Grenadini", kod: "VC" },
  { naziv: "Tadžikistan", kod: "TJ" },
  { naziv: "Tajland", kod: "TH" },
  { naziv: "Tajvan", kod: "TW" },
  { naziv: "Tanzanija", kod: "TZ" },
  { naziv: "Togo", kod: "TG" },
  { naziv: "Tokelau", kod: "TK" },
  { naziv: "Tonga", kod: "TO" },
  { naziv: "Trinidad i Tobago", kod: "TT" },
  { naziv: "Tunis", kod: "TN" },
  { naziv: "Turkmenistan", kod: "TM" },
  { naziv: "Turks i Kejkos ostrva", kod: "TC" },
  { naziv: "Turska", kod: "TR" },
  { naziv: "Tuvalu", kod: "TV" },
  { naziv: "Uganda", kod: "UG" },
  { naziv: "Ujedinjeni Arapski Emirati", kod: "AE" },
  { naziv: "Ukrajina", kod: "UA" },
  { naziv: "Urugvaj", kod: "UY" },
  { naziv: "Uzbekistan", kod: "UZ" },
  { naziv: "Valis i Futuna", kod: "WF" },
  { naziv: "Vanuatu", kod: "VU" },
  { naziv: "Vatikan", kod: "VA" },
  { naziv: "Velika Britanija", kod: "GB" },
  { naziv: "Venecuela", kod: "VE" },
  { naziv: "Vijetnam", kod: "VN" },
  { naziv: "Zambija", kod: "ZM" },
  { naziv: "Zapadna Sahara", kod: "EH" },
  { naziv: "Zelenortska Republika", kod: "CV" },
  { naziv: "Zimbabve", kod: "ZW" },
];
